### ISSUE TITLE
how to encrypt swauthkey,In a production environment, it's too insecure

### ISSUE THREAD

**Issue by osmboy** [gholt/swauth#81]

**Comment by gholt** [comment]
Hi!

Development for Swauth was transferred to a new team, https://github.com/openstack/swauth

It seems they have Issues turned off on that project; I'm not sure where you're suppose to offer feedback now.

I would try @onovy and maybe he knows.

**Comment by onovy** [comment]
Hi,

please report bugs here: https://bugs.launchpad.net/swauth

Thanks.
